# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryServiceStub(object):
    """
    LibraryService defines all core library operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBook = channel.unary_unary(
                '/library.LibraryService/CreateBook',
                request_serializer=library__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=library__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/library.LibraryService/ListBooks',
                request_serializer=library__pb2.Empty.SerializeToString,
                response_deserializer=library__pb2.BooksResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/library.LibraryService/UpdateBook',
                request_serializer=library__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=library__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/library.LibraryService/DeleteBook',
                request_serializer=library__pb2.IdRequest.SerializeToString,
                response_deserializer=library__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.CreateMember = channel.unary_unary(
                '/library.LibraryService/CreateMember',
                request_serializer=library__pb2.CreateMemberRequest.SerializeToString,
                response_deserializer=library__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/library.LibraryService/ListMembers',
                request_serializer=library__pb2.Empty.SerializeToString,
                response_deserializer=library__pb2.MembersResponse.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/library.LibraryService/UpdateMember',
                request_serializer=library__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=library__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.DeleteMember = channel.unary_unary(
                '/library.LibraryService/DeleteMember',
                request_serializer=library__pb2.IdRequest.SerializeToString,
                response_deserializer=library__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.BorrowBook = channel.unary_unary(
                '/library.LibraryService/BorrowBook',
                request_serializer=library__pb2.BorrowBookRequest.SerializeToString,
                response_deserializer=library__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/library.LibraryService/ReturnBook',
                request_serializer=library__pb2.ReturnBookRequest.SerializeToString,
                response_deserializer=library__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ListBorrowedBooks = channel.unary_unary(
                '/library.LibraryService/ListBorrowedBooks',
                request_serializer=library__pb2.ListBorrowedBooksRequest.SerializeToString,
                response_deserializer=library__pb2.BorrowedBooksResponse.FromString,
                _registered_method=True)


class LibraryServiceServicer(object):
    """
    LibraryService defines all core library operations
    """

    def CreateBook(self, request, context):
        """Books
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMember(self, request, context):
        """Members
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBook(self, request, context):
        """Borrowing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowedBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=library__pb2.CreateBookRequest.FromString,
                    response_serializer=library__pb2.MessageResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=library__pb2.Empty.FromString,
                    response_serializer=library__pb2.BooksResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=library__pb2.UpdateBookRequest.FromString,
                    response_serializer=library__pb2.MessageResponse.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=library__pb2.IdRequest.FromString,
                    response_serializer=library__pb2.MessageResponse.SerializeToString,
            ),
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=library__pb2.CreateMemberRequest.FromString,
                    response_serializer=library__pb2.MessageResponse.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=library__pb2.Empty.FromString,
                    response_serializer=library__pb2.MembersResponse.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=library__pb2.UpdateMemberRequest.FromString,
                    response_serializer=library__pb2.MessageResponse.SerializeToString,
            ),
            'DeleteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMember,
                    request_deserializer=library__pb2.IdRequest.FromString,
                    response_serializer=library__pb2.MessageResponse.SerializeToString,
            ),
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=library__pb2.BorrowBookRequest.FromString,
                    response_serializer=library__pb2.MessageResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=library__pb2.ReturnBookRequest.FromString,
                    response_serializer=library__pb2.MessageResponse.SerializeToString,
            ),
            'ListBorrowedBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowedBooks,
                    request_deserializer=library__pb2.ListBorrowedBooksRequest.FromString,
                    response_serializer=library__pb2.BorrowedBooksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.LibraryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """
    LibraryService defines all core library operations
    """

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateBook',
            library__pb2.CreateBookRequest.SerializeToString,
            library__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBooks',
            library__pb2.Empty.SerializeToString,
            library__pb2.BooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/UpdateBook',
            library__pb2.UpdateBookRequest.SerializeToString,
            library__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/DeleteBook',
            library__pb2.IdRequest.SerializeToString,
            library__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateMember',
            library__pb2.CreateMemberRequest.SerializeToString,
            library__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListMembers',
            library__pb2.Empty.SerializeToString,
            library__pb2.MembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/UpdateMember',
            library__pb2.UpdateMemberRequest.SerializeToString,
            library__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/DeleteMember',
            library__pb2.IdRequest.SerializeToString,
            library__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/BorrowBook',
            library__pb2.BorrowBookRequest.SerializeToString,
            library__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ReturnBook',
            library__pb2.ReturnBookRequest.SerializeToString,
            library__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowedBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBorrowedBooks',
            library__pb2.ListBorrowedBooksRequest.SerializeToString,
            library__pb2.BorrowedBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
